<x-layouts.admin title="Dashboard" breadcrumb="Resumen">
    <section data-organizational-dashboard class="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6">
        <div class="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-semibold">Resumen de la organización</h2><p class="mt-1 text-sm text-slate-500">Colaboradores, evaluaciones y diagnósticos disponibles para tu cuenta.</p></div><button id="dashboard-reload" type="button" class="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm text-blue-600">Actualizar</button></div>
        <div class="mb-5 flex flex-wrap gap-3 text-sm text-slate-500"><p id="dashboard-status" role="status">Cargando información…</p><a href="{{ route('login') }}" class="text-blue-600">Iniciar sesión</a></div>
        <div id="dashboard-metrics" class="grid grid-cols-2 gap-3 lg:grid-cols-4" aria-label="Indicadores de la organización"></div>
        <div class="mt-6 grid gap-5 lg:grid-cols-2">
            <article class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Estado de las evaluaciones</h2><p class="mt-1 text-xs text-slate-500">Distribución de las evaluaciones registradas.</p><div id="evaluation-distribution" class="mt-5 grid gap-4"><p class="text-sm text-slate-500">Sin datos disponibles.</p></div></article>
            <article class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap justify-between gap-3"><h2 class="font-semibold">Accesos rápidos</h2></div><div class="mt-5 grid gap-3"><a href="{{ route('collaborators.index') }}" class="rounded-lg border border-slate-200 px-4 py-3 text-sm text-blue-600 hover:bg-blue-50">Consultar colaboradores →</a><a href="#habilidades" class="rounded-lg border border-slate-200 px-4 py-3 text-sm text-blue-600 hover:bg-blue-50">Explorar catálogo de habilidades →</a></div><p class="mt-5 text-sm leading-6 text-slate-500">El resumen se calcula a partir de los registros consultados. Los resultados sin evaluación no se cuentan como cero.</p></article>
        </div>
        <article class="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Diagnósticos organizacionales</h2><div id="dashboard-diagnostics" class="mt-4 grid gap-3"><p class="text-sm text-slate-500">Sin diagnósticos disponibles.</p></div></article>
    </section>
</x-layouts.admin>